#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>
#include <vector>
#include <iostream>

#include "../../../../RootTreeProducers/interface/Track.h"
#include "../../../../RootTreeProducers/interface/GenParticle.h"
#ifdef __CINT__
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ class Track+;
#pragma link C++ class std::vector<Track>+;
#pragma link C++ class GenParticle+;
#pragma link C++ class std::vector<GenParticle>+;
#endif

void copytree() {
  // Example of Root macro to copy a subset of a Tree to a new Tree
  // Only selected entries are copied to the new Tree.
  // The input file has been generated by the program in $ROOTSYS/test/Event
  // with   Event 1000 1 99 1
  //Author: Rene Brun

  //Get old file, old tree and set top branch address
  // TFile *oldfile = new TFile("/uscms_data/d3/demattia/DisplacedLeptons/RefittedStandAloneMuons/Analysis/CMSSW_5_3_7/src/Analysis/TrackingEfficiencyFromCosmics/test/Macros/TreeAnalyzers/NewMC_PPReco/cosmicMuons1Leg.root");
  // TFile *oldfile = new TFile("/eos/uscms/store/user/lpcdve/noreplica/Cosmics/Trees_SA/cosmicMuons1Leg_RunA.root");
  // TFile *oldfile = new TFile("/eos/uscms/store/user/lpcdve/noreplica/Cosmics/Trees_SA/cosmicMuons1Leg_RunB.root");
  TFile *oldfile = new TFile("/eos/uscms/store/user/lpcdve/noreplica/Cosmics/Trees_SA/cosmicMuons1Leg_RunC.root");
  TTree *oldtree = (TTree*)oldfile->Get("T");
  Long64_t nentries = oldtree->GetEntries();

  UInt_t event;
  UInt_t run;
  std::vector<Track>   *tracks;
  // std::vector<Track>   *muons;
  // std::vector<GenParticle> *genParticles;

  oldtree->SetBranchAddress("event",&event);
  oldtree->SetBranchAddress("run",&run);
  oldtree->SetBranchAddress("tracks",&tracks);
  // oldtree->SetBranchAddress("muons",&muons);
  // oldtree->SetBranchAddress("genParticles",&genParticles);

  //Create a new file + a clone of old tree in new file
  TFile *newfile = new TFile("small.root","recreate");
  TTree *newtree = oldtree->CloneTree(0);

  std::cout << "entry = " << 0 << std::endl;
  for (Long64_t i=0;i<nentries; i++) {
    if( i%(nentries/10) == 0 ) std::cout << "processed " << i/(nentries/10) << "%" << std::endl;
    oldtree->GetEntry(i);
    std::vector<Track>::const_iterator jt = tracks->begin();
    bool goodMuons = false;
    for( ; jt != tracks->end(); ++jt ) {
      goodMuons = true;
    }
    if( goodMuons ) newtree->Fill();
    // if( nentries > 100 ) break;
  }
  newtree->Print();
  newtree->AutoSave();
  delete oldfile;
  delete newfile;
}
